language: go
go:
  - "1.19"

before_install:
  - cp ./config.yml.dist ./config.yml
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)