port: 83
database:
  host: 127.0.0.1
  port: 5427
  name: exampledb
  user: exampleuser
  password: 12345
  max_connections: 10
jwt:
  secret: 1234567890
  access_token_lifetime: 30000 # Seconds
  refresh_token_lifetime: 604800 # Seconds (1 week)
