version: '3.9'

services:
  db:
    image: postgres:latest
    ports:
      - 54335:5432
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=example_db
      - POSTGRES_USER=example_user
      - POSTGRES_PASSWORD=12345
      - PGDATA="/var/lib/postgresql/data/pgdata"
