// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/jmoiron/sqlx"
	"github.com/kachit/golang-api-skeleton/api"
	"github.com/kachit/golang-api-skeleton/config"
	"github.com/kachit/golang-api-skeleton/infrastructure"
	"github.com/kachit/golang-api-skeleton/models"
)

// Injectors from wire.go:

func InitializeConfig(configPath string) (*config.Config, error) {
	configConfig, err := config.NewConfig(configPath)
	if err != nil {
		return nil, err
	}
	return configConfig, nil
}

func InitializeDatabase(cfg *config.Config) (*sqlx.DB, error) {
	db, err := infrastructure.NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	return db, nil
}

func InitializeLogger(cfg *config.Config) (infrastructure.Logger, error) {
	logger := infrastructure.NewLogger(cfg)
	return logger, nil
}

func InitializeRepositoriesFactory(db *sqlx.DB) (*models.RepositoriesFactory, error) {
	repositoriesFactory := models.NewRepositoriesFactory(db)
	return repositoriesFactory, nil
}

func InitializeUsersResource(container *infrastructure.Container) (*api.UsersResource, error) {
	usersResource := api.NewUsersResource(container)
	return usersResource, nil
}

func InitializeErrorsResource(container *infrastructure.Container) (*api.ErrorsResource, error) {
	errorsResource := api.NewErrorsResource(container)
	return errorsResource, nil
}

func InitializeContainer(configPath string) (*infrastructure.Container, error) {
	configConfig, err := InitializeConfig(configPath)
	if err != nil {
		return nil, err
	}
	logger, err := InitializeLogger(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := InitializeDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	repositoriesFactory, err := InitializeRepositoriesFactory(db)
	if err != nil {
		return nil, err
	}
	container := &infrastructure.Container{
		Config: configConfig,
		Logger: logger,
		DB:     db,
		RF:     repositoriesFactory,
	}
	return container, nil
}
