// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/jmoiron/sqlx"
	"github.com/kachit/golang-api-skeleton/api"
	"github.com/kachit/golang-api-skeleton/config"
	"github.com/kachit/golang-api-skeleton/infrastructure"
	"github.com/kachit/golang-api-skeleton/services"
)

// Injectors from wire.go:

func InitializeConfig(configPath string) (*config.Config, error) {
	configConfig, err := config.NewConfig(configPath)
	if err != nil {
		return nil, err
	}
	return configConfig, nil
}

func InitializeDatabase(cfg *config.Config) (*sqlx.DB, error) {
	db, err := infrastructure.NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	return db, nil
}

func InitializeUsersResource(db *sqlx.DB) (*api.UsersResource, error) {
	usersService := services.NewUsersService(db)
	usersResource := api.NewUsersResource(usersService)
	return usersResource, nil
}
