package migrations

import (
	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

func m202203011240CreateUsersTable() *gormigrate.Migration {
	return &gormigrate.Migration{
		ID: "202203011240_create_users_table",
		Migrate: func(tx *gorm.DB) error {
			return tx.Exec(`CREATE TABLE "users" (
								  "id" int4 GENERATED BY DEFAULT AS IDENTITY,
								  "name" varchar(100) NOT NULL,
								  "email" varchar(100) NOT NULL,
								  "password" varchar(100) NOT NULL,
								  "created_at" timestamptz(6) NOT NULL,
								  "modified_at" timestamptz(6),
								  "deleted_at" timestamptz(6),
								  PRIMARY KEY ("id"),
								  CONSTRAINT ux_users_email UNIQUE (email)
								)
								;`).Error
		},
		Rollback: func(tx *gorm.DB) error {
			return tx.Migrator().DropTable("users")
		},
	}
}
